// GENERATED by tools/gen_bindings.py from the pinned engine's Python enums.
// Selectors for disabled features are constants, not an availability guarantee.

export enum ErrorCode {
  OK = 0,
  NOMEM = 1,
  INPFILE = 2,
  RPTFILE = 3,
  OUTFILE = 4,
  PARSE = 5,
  LIFECYCLE = 6,
  BADHANDLE = 7,
  BADINDEX = 8,
  BADPARAM = 9,
  PLUGIN = 10,
  IO = 11,
  HOTSTART = 12,
  CRS = 13,
  NUMERICAL = 14,
  DEPENDENCY = 15,
  INTERNAL = 99,
}

export enum EngineState {
  NONE = 0,
  CREATED = 1,
  OPENED = 2,
  INITIALIZED = 3,
  STARTED = 4,
  RUNNING = 5,
  ENDED = 6,
  CLOSED = 7,
  BUILDING = 8,
}

export enum WarnCode {
  NONE = 0,
  HOTSTART_MISSING = 1,
  UNKNOWN_SECTION = 2,
  UNKNOWN_OPTION = 3,
  DEPRECATED_KW = 4,
  PLUGIN_INIT = 5,
  NUMERICAL = 6,
  STABILITY_LIMIT = 7,
}

export enum ObjectType {
  GAGE = 0,
  SUBCATCH = 1,
  NODE = 2,
  LINK = 3,
  POLLUT = 4,
  LANDUSE = 5,
  TIMESER = 6,
  TABLE = 7,
  RDII = 8,
  UNITHYD = 9,
  SNOWMELT = 10,
  SHAPE = 11,
  LID = 12,
}

export enum FlowUnits {
  CFS = 0,
  GPM = 1,
  MGD = 2,
  CMS = 3,
  LPS = 4,
  MLD = 5,
}

export enum RouteModel {
  STEADY = 0,
  KINWAVE = 1,
  DYNWAVE = 2,
  FV = 3,
}

export enum NodeType {
  JUNCTION = 0,
  OUTFALL = 1,
  STORAGE = 2,
  DIVIDER = 3,
}

export enum LinkType {
  CONDUIT = 0,
  PUMP = 1,
  ORIFICE = 2,
  WEIR = 3,
  OUTLET = 4,
}

export enum OrificeType {
  SIDE = 0,
  BOTTOM = 1,
}

export enum WeirType {
  TRANSVERSE = 0,
  SIDEFLOW = 1,
  VNOTCH = 2,
  TRAPEZOIDAL = 3,
  ROADWAY = 4,
}

export enum OutletRatingType {
  FUNCTIONAL_HEAD = 0,
  FUNCTIONAL_DEPTH = 1,
  TABULAR_HEAD = 2,
  TABULAR_DEPTH = 3,
}

export enum OutfallType {
  FREE = 0,
  NORMAL = 1,
  FIXED = 2,
  TIDAL = 3,
  TIMESERIES = 4,
}

export enum StorageShape {
  TABULAR = 0,
  FUNCTIONAL = 1,
  CYLINDRICAL = 2,
  CONICAL = 3,
  PARABOLOID = 4,
  PYRAMIDAL = 5,
}

export enum XSectShape {
  CIRCULAR = 0,
  FILLED_CIRCULAR = 1,
  RECT_CLOSED = 2,
  RECT_OPEN = 3,
  TRAPEZOIDAL = 4,
  TRIANGULAR = 5,
  PARABOLIC = 6,
  POWER = 7,
  MODBASKETHANDLE = 8,
  EGGSHAPED = 9,
  HORSESHOE = 10,
  GOTHIC = 11,
  CATENARY = 12,
  SEMIELLIPTICAL = 13,
  BASKETHANDLE = 14,
  SEMICIRCULAR = 15,
  RECT_TRIANG = 16,
  RECT_ROUND = 17,
  HORIZ_ELLIPSE = 18,
  VERT_ELLIPSE = 19,
  ARCH = 20,
  IRREGULAR = 21,
  CUSTOM = 22,
  FORCE_MAIN = 23,
  STREET_XSECT = 24,
  DUMMY = 25,
}

export enum InfilModel {
  HORTON = 0,
  MOD_HORTON = 1,
  GREEN_AMPT = 2,
  MOD_GREEN_AMPT = 3,
  CURVE_NUMBER = 4,
}

export enum GageDataSource {
  TIMESERIES = 0,
  FILE = 1,
}

export enum GageRainType {
  INTENSITY = 0,
  VOLUME = 1,
  CUMULATIVE = 2,
}

export enum ConcentrationUnits {
  MG_PER_L = 0,
  UG_PER_L = 1,
  COUNT_PER_L = 2,
}

export enum BuildupFunc {
  NONE = 0,
  POW = 1,
  EXP = 2,
  SAT = 3,
  EXT = 4,
}

export enum WashoffFunc {
  NONE = 0,
  EXP = 1,
  RC = 2,
  EMC = 3,
}

export enum LidType {
  BIO_CELL = 0,
  RAIN_GARDEN = 1,
  GREEN_ROOF = 2,
  INFIL_TRENCH = 3,
  PERM_PAVEMENT = 4,
  RAIN_BARREL = 5,
  ROOFTOP_DISCONN = 6,
  VEGETATIVE_SWALE = 7,
}

export enum AquiferParam {
  POROSITY = 0,
  WILTING_POINT = 1,
  FIELD_CAPACITY = 2,
  CONDUCTIVITY = 3,
  CONDUCT_SLOPE = 4,
  TENSION_SLOPE = 5,
  UPPER_EVAP_FRAC = 6,
  LOWER_EVAP_DEPTH = 7,
  LOWER_LOSS_COEFF = 8,
  BOTTOM_ELEV = 9,
  WATER_TABLE_ELEV = 10,
  UPPER_MOISTURE = 11,
}

export enum GwfType {
  LATERAL = 0,
  DEEP = 1,
}

export enum OutSubcatchVar {
  RAINFALL = 0,
  SNOW_DEPTH = 1,
  EVAP = 2,
  INFIL = 3,
  RUNOFF = 4,
  GW_FLOW = 5,
  GW_ELEV = 6,
  SOIL_MOIST = 7,
  POLLUT_BASE = 8,
}

export enum OutNodeVar {
  DEPTH = 0,
  HEAD = 1,
  VOLUME = 2,
  LATERAL_INFLOW = 3,
  TOTAL_INFLOW = 4,
  OVERFLOW = 5,
  POLLUT_BASE = 6,
}

export enum OutLinkVar {
  FLOW = 0,
  DEPTH = 1,
  VELOCITY = 2,
  VOLUME = 3,
  CAPACITY = 4,
  POLLUT_BASE = 5,
}

export enum OutSystemVar {
  TEMPERATURE = 0,
  RAINFALL = 1,
  SNOW_DEPTH = 2,
  INFIL = 3,
  RUNOFF = 4,
  DW_INFLOW = 5,
  GW_INFLOW = 6,
  RDII_INFLOW = 7,
  EXT_INFLOW = 8,
  TOTAL_INFLOW = 9,
  FLOODING = 10,
  OUTFLOW = 11,
  STORAGE = 12,
  EVAP = 13,
  PET = 14,
  LAT_INFLOW = 9,
}

export enum ForcingMode {
  REPLACE = 1,
  ADD = 2,
}

export enum ForcingTarget {
  NODE = 0,
  LINK = 1,
  SUBCATCH = 2,
  GAGE = 3,
  CLIMATE = 4,
}

export enum PatternType {
  MONTHLY = 0,
  DAILY = 1,
  HOURLY = 2,
  WEEKEND = 3,
}

export enum RunoffTotal {
  RAINFALL = 0,
  EVAP = 1,
  INFIL = 2,
  RUNOFF = 3,
  SNOWREMOV = 4,
  INITSTORE = 5,
  FINALSTORE = 6,
  INITSNOW = 7,
  FINALSNOW = 8,
}

export enum RoutingTotal {
  DRY_WEATHER = 0,
  WET_WEATHER = 1,
  GW_INFLOW = 2,
  RDII = 3,
  EXTERNAL = 4,
  FLOODING = 5,
  OUTFLOW = 6,
  EVAP_LOSS = 7,
  SEEP_LOSS = 8,
  INIT_STORAGE = 9,
  FINAL_STORAGE = 10,
  FORCING_INFLOW = 11,
  LINK_GW_INFLOW = 13,
  COUPLING_OUT = 12,
}

export enum DividerType {
  CUTOFF = 0,
  OVERFLOW = 1,
  TABULAR = 2,
  WEIR = 3,
}

export enum ForcingType {
  NODE_LAT_INFLOW = 0,
  NODE_HEAD_BOUNDARY = 1,
  NODE_QUALITY = 2,
  LINK_FLOW = 3,
  LINK_SETTING = 4,
  SUBCATCH_RAINFALL = 5,
  SUBCATCH_EVAP = 6,
  GAGE_RAINFALL = 7,
  CLIMATE_TEMPERATURE = 8,
  CLIMATE_WIND = 9,
  SUBCATCH_SNOWFALL = 10,
  CLIMATE_EVAP = 11,
  LINK_QUALITY = 12,
  ELEM_AIR_TEMPERATURE = 13,
  ELEM_HUMIDITY = 14,
  ELEM_WIND_SPEED = 15,
  ELEM_SHORTWAVE = 16,
  LINK_SEEPAGE = 17,
}

export enum ForcingPersist {
  RESET = 0,
  PERSIST = 1,
}

export enum SurfaceForcingMode {
  NONE = 0,
  OVERRIDE = 1,
  ADD = 2,
}

export enum SurfaceBoundaryType {
  WALL = 0,
  NORMAL_FLOW = 1,
  SPECIFIED_STAGE = 2,
  SPECIFIED_FLOW = 3,
  RATING_CURVE = 4,
}

export enum SurfaceInfilMethod {
  HORTON = 0,
  MOD_HORTON = 1,
  GREEN_AMPT = 2,
  MOD_GREEN_AMPT = 3,
  CURVE_NUMBER = 4,
  CONSTANT = 5,
}

export enum SurfaceInfilDest {
  LOST = 0,
  SUBCATCH_AQUIFER = 1,
  AQUIFER_2D = 2,
}

export enum RefType {
  NODE = 0,
  LINK = 1,
  SUBCATCH = 2,
  GAGE = 3,
  TABLE = 4,
  TRANSECT = 5,
  INLET_USAGE = 6,
  EXT_INFLOW = 7,
  DWF_INFLOW = 8,
  RDII_ASSIGN = 9,
  TREATMENT = 10,
  LID_USAGE = 11,
  SNOWPACK = 12,
  HYDROGRAPH = 13,
  POLLUTANT = 14,
  PATTERN = 15,
  AQUIFER = 16,
  LID_CONTROL = 17,
  STREET = 18,
  INLET_DESIGN = 19,
  LANDUSE = 20,
  CONTROL_RULE = 21,
}

export enum TableType {
  TIMESERIES = 0,
  CURVE_STORAGE = 1,
  CURVE_DIVERSION = 2,
  CURVE_RATING = 3,
  CURVE_SHAPE = 4,
  CURVE_CONTROL = 5,
  CURVE_TIDAL = 6,
  CURVE_PUMP1 = 7,
  CURVE_PUMP2 = 8,
  CURVE_PUMP3 = 9,
  CURVE_PUMP4 = 10,
  CURVE_PUMP5 = 11,
}

export enum FilePathRole {
  RAINFALL = 1,
  RUNOFF = 2,
  RDII = 3,
  INFLOWS = 4,
  OUTFLOWS = 5,
  HOTSTART_USE = 6,
  CLIMATE_TEMP = 7,
  HOTSTART_SAVE = 8,
  RAINGAGE_DATA = 9,
  TIMESERIES_DATA = 10,
  MESH_2D = 11,
  OUTPUT_2D = 12,
  LID_REPORT = 13,
}

export enum UserFlagType {
  BOOLEAN = 0,
  INTEGER = 1,
  REAL = 2,
  STRING = 3,
}

export enum HeatFluxModule {
  SURFACE_EXCHANGE = 0,
  RADIATIVE_EXCHANGE = 1,
  LAYER_CONDUCTION = 2,
}

export enum HeatShortwaveMode {
  CONSTANT = 0,
  TIMESERIES = 1,
  COMPUTED = 2,
}

export enum HeatRadiativeParam {
  SHORTWAVE = 0,
  ALBEDO = 1,
  SHADE_FACTOR = 2,
  SKY_VIEW = 3,
  EMISS_WATER = 4,
  EMISS_LANDCOVER = 5,
  ATM_EMISS_COEFF = 6,
  LW_REFLECTION = 7,
}

export enum HeatSolarParam {
  LATITUDE = 0,
  LONGITUDE = 1,
  TIMEZONE = 2,
  ELEVATION = 3,
  TURBIDITY_380 = 4,
  TURBIDITY_500 = 5,
  PRECIP_WATER = 6,
  OZONE = 7,
  GROUND_ALBEDO = 8,
}

export enum HeatCloudParam {
  FRACTION = 0,
  SW_ATTEN_K = 1,
  SW_ATTEN_N = 2,
  LW_CLOUD_K = 3,
}

export enum HeatSourceKind {
  RAINFALL = 0,
  DWF = 1,
  GW = 2,
  RDII = 3,
  EXTERNAL_INFLOW = 4,
  IFACE = 5,
  INITIAL_STATE = 6,
}

export enum WaterAgeSource {
  RAINFALL = 0,
  DWF = 1,
  GW = 2,
  RDII = 3,
  EXTERNAL_INFLOW = 4,
  IFACE = 5,
  INITIAL_STATE = 6,
}

export enum ReactionScope {
  TERM = 0,
  PIPE = 1,
  TANK = 2,
}

export enum ReactionExprForm {
  NONE = 0,
  RATE = 1,
  EQUIL = 2,
  FORMULA = 3,
}

export enum InletType {
  GRATE = 0,
  CURB = 1,
  COMBO = 2,
  SLOTTED = 3,
  DROP_GRATE = 4,
  DROP_CURB = 5,
  CUSTOM = 6,
}

export enum GrateType {
  P_BAR_50 = 0,
  P_BAR_50x100 = 1,
  P_BAR_30 = 2,
  CURVED_VANE = 3,
  TILT_BAR_45 = 4,
  TILT_BAR_30 = 5,
  RETICULINE = 6,
  GENERIC = 7,
}

export enum ThroatType {
  HORIZONTAL = 0,
  INCLINED = 1,
  VERTICAL = 2,
}

export enum InletCurveKind {
  NONE = 0,
  DIVERSION = 1,
  RATING = 2,
}

export enum InletPlacement {
  AUTOMATIC = 0,
  ON_GRADE = 1,
  ON_SAG = 2,
}

export enum InletHostKind {
  LINK = 0,
  NODE = 1,
}

export enum EvapType {
  CONSTANT = 0,
  MONTHLY = 1,
  TIMESERIES = 2,
  TEMPERATURE = 3,
  FILE = 4,
}

export enum TempSource {
  NONE = 0,
  TIMESERIES = 1,
  FILE = 2,
}

export enum WindType {
  MONTHLY = 0,
  FILE = 1,
}

export enum HumidityType {
  CONSTANT = 0,
  MONTHLY = 1,
  TIMESERIES = 2,
}

export enum HumidityVar {
  RELATIVE = 0,
  DEWPOINT = 1,
}

export enum HeatElemKind {
  NODE = 0,
  LINK = 1,
}

export enum InpProfile {
  FULL = 0,
  SWMM5 = 1,
  SWMM5_STOCK = 2,
}

export enum TransportDispersionMode {
  OFF = 0,
  FISCHER = 1,
  VALUE = 2,
}

export enum UnitSystem {
  UNITS_US = 0,
  UNITS_SI = 1,
}

export enum TransportDomain {
  RUNOFF = 0,
  GROUNDWATER = 1,
  NETWORK_1D = 2,
  SURFACE_2D = 3,
}

export enum TransportClass {
  POLLUTANTS = 0,
  MSX = 1,
  AGE = 2,
  TEMPERATURE = 3,
}

export enum TransportState {
  ENABLED = 0,
  DISABLED_BY_USER = 1,
  UNAVAILABLE = 2,
}

export enum CellScope {
  GLOBAL = 0,
  TAG = 1,
  CELL = 2,
}

export enum GroundwaterSoil {
  RUSSO = 0,
  GARDNER = 1,
  BROOKS_COREY = 2,
  VAN_GENUCHTEN = 3,
}

export enum GroundwaterClosure {
  AUTO = -1,
  CLOSED_FORM = 0,
  ENSLAVED = 1,
  SIGMA = 2,
}

export enum GroundwaterVariable {
  HG = 0,
  HU = 1,
  TABLE_EL = 2,
  Q0 = 3,
  QLAT = 4,
  QNODE = 5,
  QDEEP = 6,
  QET = 7,
  DUNNE = 8,
  QPLUS = 9,
  DT_CELL = 10,
  TIER = 11,
  CLOSURE = 12,
  QLINK = 13,
}

export enum GroundwaterLedger {
  RECHARGE = 0,
  LATERAL = 1,
  DEEP = 2,
  NODE = 3,
  DUNNE = 4,
  CAPRISE = 5,
  ET = 6,
  INFIL_IN = 7,
  INIT_STORAGE = 8,
  STORAGE = 9,
  LINK = 10,
  SOURCE_IN = 11,
  SOURCE_OUT = 12,
}

export enum GroundwaterZone {
  SAT = 0,
  UNSAT = 1,
}

export enum GroundwaterSpeciesLedger {
  INIT = 0,
  STORAGE = 1,
  INFIL_IN = 2,
  NODE_IN = 3,
  LINK_IN = 4,
  LATERAL_NET = 5,
  DEEP_OUT = 6,
  NODE_OUT = 7,
  LINK_OUT = 8,
  DUNNE_OUT = 9,
  ET_OUT = 10,
  REACTED = 11,
  RESIDUAL = 12,
  SOURCE_IN = 13,
  SOURCE_OUT = 14,
}

export enum GroundwaterTransportZone {
  SAT = 0,
  UNSAT = 1,
  LAYER = 2,
}

export enum TraceStatus {
  OK = 0,
  INVALID = -1,
  IO = -2,
  MISMATCH = -3,
  CANCELLED = -4,
  SOLVER = -5,
  NO_HDF5 = -6,
}

export enum TraceDirection {
  DOWNSTREAM = 0,
  UPSTREAM = 1,
}

export enum TraceTerminal {
  OUTFALL = 0,
  LOSS = 1,
  SOURCE = 2,
  RETAINED = 3,
  UNRESOLVED = 4,
  CIRCULATION = 5,
}
